services:
  pacha:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .pacha.env
    ports:
      - "5001:5001"
    extra_hosts:
      - local.hasura.dev=host-gateway
    volumes:
      - ./data/pacha.db:/app/pacha.db
volumes:
  data: