version: '3'
services:
  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14250:14250"  # gRPC collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger


# version: '3'
# services:
#   # Jaeger
#   jaeger:
#     image: jaegertracing/all-in-one:latest
#     ports:
#       - "16686:16686"  # Jaeger UI
#       - "14250:14250"  # OTLP gRPC
#       - "14268:14268"  # Jaeger HTTP thrift
#       - "6831:6831/udp"  # Jaeger thrift compact
#     environment:
#       - COLLECTOR_OTLP_ENABLED=true

#   # OpenTelemetry Collector
#   otel-collector:
#     image: otel/opentelemetry-collector:0.86.0
#     command: ["--config=/etc/otel-collector-config.yaml"]
#     volumes:
#       - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
#     ports:
#       - "4317:4317"   # OTLP gRPC receiver
#       - "4318:4318"   # OTLP HTTP receiver
#       - "8888:8888"   # Prometheus metrics exposed by the collector
#       - "8889:8889"   # Prometheus exporter metrics
#     depends_on:
#       - jaeger
